on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:

name: Rust Continuous integration

jobs:
  test:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:  
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: "clippy,rustfmt"
      - name: check
        run: cargo check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:  
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: "clippy,rustfmt"
      -
        run: cargo build

  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:  
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: "clippy,rustfmt"
      - 
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:  
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: "clippy,rustfmt"
      - 
        run: cargo clippy -- -D warnings